export const phraseStarter = [
	"I can't believe",
	"Look's like",
	"Feel's like",
	"Isn't it",
	"Well isn't",
	"I hope",
	"I know",
	"What a",
	"If only",
	"I did",
	"I have to say",
	"You know",
	"It's only",
	"Every time I",
	"Guess what",
	"On a more personal note",
	"I'm happy to",
	"I would like",
	"I am",
	"Here’s what",
	"You kind",
	"When it comes to",
	"One thing",
	"I like what",
	"Don't you",
	"It's easy",
	"Is there",
	"I should",
	"As you",
	"Let’s",
	"Please",
	"You've",
	"I promise",
	"I've got",
	"I bet",
	"The most",
	"I want",
	"I'm sure",
	"I'm not",
	"I'm excited",
	"Many",
	"My",
	"While",
	"This is",
	"Quick",
	"There",
	"I've just",
	"If you're",
	"Are you",
	"Let me",
	"I've read",
	"Read",
	"Since",
	"Let’s say",
	"What if",
	"Is your",
	"Nothing",
	"Just read",
	"How does",
	"Just ran",
	"When the",
	"Let's talk",
	"A great",
	"After finding",
	"How are",
	"Dealing with",
	"I found",
	"Today I",
	"I understand",
	"Thank you",
	"Just left",
	"I'd like",
	"I'm writing",
	"This might",
	"Love what",
	"Looking at",
	"You probably",
	"I'm doing",
	"As we",
	"Saw that",
	"I hightly",
	"Just wondering",
	"I saw",
	"Want to",
	"According to",
	"I'll",
	"You mentioned",
	"There’s no denying that",
	"Let’s face it",
	"I think it’s safe to assume that",
	"This should come as a suprise but",
	"I can definitely see",
	"Would I be wrong to",
	"Is it just me or",
	"We've noticed",
	"Let's be honest",
	"One thing",
	"Congrats on",
	"I was checking",
	"It's great",
	"Let me say this",
	"Okay now",
	"True truth is",
	"I'll be the first to admit",
	"Just when I",
	"I never",
	"This is the first time",
	"Nowadays",
	"Speaking of",
	"In my opinion",
	"As you know",
	"Finally",
	"It's almost as if",
	"I read",
	"I saw that",
	"I heard",
	"A colleague told me",
	"I found",
	"I wish",
	"There's only",
	"If you",
	"It's only right",
	"How did I",
	"Can we",
	"May I",
	"Thanks for",
	"I really appreciate",
	"Would you",
	"If I",
	"Are you",
	"Do you",
	"Would you",
	"Did you",
	"Have you",
  ];
